"""adding columns

Revision ID: 22dd3865ba5f
Revises: 633f17eec320
Create Date: 2019-11-07 10:55:59.367699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dd3865ba5f'
down_revision = '633f17eec320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardgame', sa.Column('player_number_max', sa.Integer(), nullable=True))
    op.add_column('boardgame', sa.Column('player_number_min', sa.Integer(), nullable=True))
    op.add_column('boardgame', sa.Column('playtime_low', sa.Integer(), nullable=True))
    op.add_column('boardgame', sa.Column('playtime_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boardgame', 'playtime_max')
    op.drop_column('boardgame', 'playtime_low')
    op.drop_column('boardgame', 'player_number_min')
    op.drop_column('boardgame', 'player_number_max')
    # ### end Alembic commands ###
