"""new boardgame

Revision ID: aadb5e49c991
Revises: 1e4a44f23495
Create Date: 2019-11-06 10:02:02.489844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadb5e49c991'
down_revision = '1e4a44f23495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardgame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boardgame')
    # ### end Alembic commands ###
