"""empty message

Revision ID: dfe169b9942c
Revises: 22dd3865ba5f
Create Date: 2020-03-20 17:21:56.408066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe169b9942c'
down_revision = '22dd3865ba5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardgame', sa.Column('difficulty', sa.String(length=140), nullable=True))
    op.add_column('boardgame', sa.Column('genre', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boardgame', 'genre')
    op.drop_column('boardgame', 'difficulty')
    # ### end Alembic commands ###
